menus:
  主页: /
  关于: /about/
  分类: /categories/
  标签: /tags/
  友情链接: /links/

social:
  GitHub: https://github.com/w4ngzhen || fa fa-github
  RSS: /atom.xml || fa fa-rss

favicon:
  small: /images/blog-site-icon.svg
  medium: /images/blog-site-icon.svg
  apple_touch_icon: /images/blog-site-icon.svg
  safari_pinned_tab: /images/blog-site-icon.svg

comments:
  comment_box:
    enable: true
    repo: blog
    owner: w4ngzhen